DROP TABLE STUDENTCOURSE;

DROP TABLE STUDENT;

DROP TABLE COURSE;

CREATE TABLE STUDENT(
SID INT(5) PRIMARY KEY AUTO_INCREMENT,
SNAME VARCHAR(30)
);

CREATE TABLE COURSE(
CID INT(5) PRIMARY KEY AUTO_INCREMENT,
CNAME VARCHAR(30)
);

CREATE TABLE STUDENTCOURSE(
SID INT(5),
CID INT(5),
CONSTRAINT FOREIGN KEY (SID) REFERENCES STUDENT (SID),
CONSTRAINT FOREIGN KEY (CID) REFERENCES COURSE (CID)
);


