DROP TABLE EMPLOYEE;

DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT(
DEPTID INT(5) PRIMARY KEY AUTO_INCREMENT,
DNAME VARCHAR(30)
);

CREATE	TABLE EMPLOYEE(
EMPID INT(5) PRIMARY KEY AUTO_INCREMENT,
ENAME VARCHAR(30),
EMAIL VARCHAR(30),
DEPTID INT(5),
CONSTRAINT FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT (DEPTID)
);


INSERT  INTO DEPARTMENT(DEPTID,DNAME) VALUES (1,'IT');

INSERT  INTO DEPARTMENT(DEPTID,DNAME) VALUES (2,'SALES');

INSERT  INTO DEPARTMENT(DEPTID,DNAME) VALUES (3,'HR');


INSERT  INTO EMPLOYEE(EMPID,ENAME,EMAIL,DEPTID) VALUES (1,'JOHN','JOHN@GMAIL.COM',1);

INSERT  INTO EMPLOYEE(EMPID,ENAME,EMAIL,DEPTID) VALUES (2,'TOM','TOM@GMAIL.COM',1);

INSERT  INTO EMPLOYEE(EMPID,ENAME,EMAIL,DEPTID) VALUES (3,'PETER','PETER@GMAIL.COM',1);

INSERT  INTO EMPLOYEE(EMPID,ENAME,EMAIL,DEPTID) VALUES (4,'BOND','BOND@GMAIL.COM',2);

INSERT  INTO EMPLOYEE(EMPID,ENAME,EMAIL,DEPTID) VALUES (5,'JAMES','JAMES@GMAIL.COM',2);

INSERT  INTO EMPLOYEE(EMPID,ENAME,EMAIL,DEPTID) VALUES (6,'BILL','BILL@GMAIL.COM',3);

