DROP TABLE PHONE;

DROP TABLE PERSON;

CREATE TABLE PERSON (
  PID INT(5) PRIMARY KEY  AUTO_INCREMENT,
  PNAME VARCHAR(30)
);

CREATE TABLE PHONE (
  PHID INT(5) PRIMARY KEY AUTO_INCREMENT,
  PNUMBER VARCHAR(10),
  PID INT(5),
  CONSTRAINT FOREIGN KEY (PID) REFERENCES PERSON (PID)
);

