DROP TABLE STUDENT;

DROP TABLE ADDRESS;

CREATE	TABLE ADDRESS(
AID INT(5) PRIMARY KEY AUTO_INCREMENT,
CITY VARCHAR(30),
ZIPCODE VARCHAR(30)
);

CREATE TABLE STUDENT(
SID INT(5) PRIMARY KEY AUTO_INCREMENT,
SNAME VARCHAR(30),
AID INT(5),
CONSTRAINT FOREIGN KEY (AID) REFERENCES ADDRESS (AID)
);
